# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8000:8000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
