version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/
  
  pgadmin:
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=m.temiz@msn.com
      - PGADMIN_DEFAULT_PASSWORD=1
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  orderdb:
     container_name: orderdb
     environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=SwN12345678
     restart: always
     ports:
        - "1433:1433"
        
  messagebroker:
     container_name: messagebroker
     hostname: ecommerce-mq
     environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
     restart: always
     ports:
        - "5672:5672"
        - "15672:15672"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ConnectionStrings__Database=Server=catalogdb; Port=5432; Database=CatalogDb; User Id=postgres; Password=postgres; Include Error Detail = true
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ConnectionStrings__Database=Server=basketdb; Port=5432; Database=BasketDb; User Id=postgres; Password=postgres; Include Error Detail = true
      - ConnectionStrings__Redis=distributedcache:6379
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
      - messagebroker
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ~/.aspnet/https:/https:ro

  discount.grpc:
     container_name: discount.grpc
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ConnectionStrings__Database=Data Source=discountdb
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1
     ports:
      - 6002:8080
      - 6062:8081
     volumes:
      - ~/.aspnet/https:/https:ro

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ConnectionStrings__Database=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFullfilment=false
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1
    depends_on:
      - orderdb
      - messagebroker
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ~/.aspnet/https:/https:ro

  yarpapigateway:
    container_name: yarpapigateway
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORT=8080
        - ASPNETCORE_HTTPS_PORT=8081
        - ASPNETCORE_URLS=https://+:8081;http://+:8080
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=1
    depends_on:
        - catalog.api
        - basket.api
        - ordering.api
    ports:
        - "6004:8080"
        - "6064:8081"
    volumes:
       - ~/.aspnet/https:/https:ro