version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  pgadmin:
    image: dpage/pgadmin4:latest
    
volumes:
  postgres_catalog:
  postgres_basket:
  pgadmin_data:
